// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-1Vt8CNX_WDbFFXhJuKrg7HjbaT6W7p0',
    appId: '1:299795092052:web:c718bc3355e26a19a413c1',
    messagingSenderId: '299795092052',
    projectId: 'purramedics-a4301',
    authDomain: 'purramedics-a4301.firebaseapp.com',
    storageBucket: 'purramedics-a4301.firebasestorage.app',
    measurementId: 'G-5NV56E4SHF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp6VCF4_trJnRW2X6SrUItjOUkScqhVAg',
    appId: '1:299795092052:android:83884ff2b5b8cf99a413c1',
    messagingSenderId: '299795092052',
    projectId: 'purramedics-a4301',
    storageBucket: 'purramedics-a4301.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw4MWCjwIp0rFSEF2lpC_nUerQl1mrRzE',
    appId: '1:299795092052:ios:f11501dbf4094487a413c1',
    messagingSenderId: '299795092052',
    projectId: 'purramedics-a4301',
    storageBucket: 'purramedics-a4301.firebasestorage.app',
    iosBundleId: 'com.example.purramedics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBw4MWCjwIp0rFSEF2lpC_nUerQl1mrRzE',
    appId: '1:299795092052:ios:f11501dbf4094487a413c1',
    messagingSenderId: '299795092052',
    projectId: 'purramedics-a4301',
    storageBucket: 'purramedics-a4301.firebasestorage.app',
    iosBundleId: 'com.example.purramedics',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-1Vt8CNX_WDbFFXhJuKrg7HjbaT6W7p0',
    appId: '1:299795092052:web:b9c22ec18e72557ca413c1',
    messagingSenderId: '299795092052',
    projectId: 'purramedics-a4301',
    authDomain: 'purramedics-a4301.firebaseapp.com',
    storageBucket: 'purramedics-a4301.firebasestorage.app',
    measurementId: 'G-RLPGPQB47V',
  );
}
